//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goals
    {
        public int GoalId { get; set; }
        public string GoalName { get; set; }
        public string Desc { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<double> Target { get; set; }
        public bool GoalType { get; set; }
        public Nullable<int> MetricId { get; set; }
        public int GoalStatusId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
