//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupGoals
    {
        public int GroupGoalId { get; set; }
        public string GoalName { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<double> Target { get; set; }
        public Nullable<int> MetricId { get; set; }
        public Nullable<int> FocusId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int GoalStatusId { get; set; }
        public int GroupUserId { get; set; }
        public Nullable<int> AssignedGroupUserId { get; set; }
        public string AssignedTo { get; set; }
        public int GroupId { get; set; }
    
        public virtual GroupGoals GroupGoals1 { get; set; }
        public virtual GroupGoals GroupGoals2 { get; set; }
    }
}
