//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialGoalEntities : DbContext
    {
        public SocialGoalEntities()
            : base("name=SocialGoalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<CommentUsers> CommentUsers { get; set; }
        public virtual DbSet<Foci> Foci { get; set; }
        public virtual DbSet<FollowRequests> FollowRequests { get; set; }
        public virtual DbSet<FollowUsers> FollowUsers { get; set; }
        public virtual DbSet<Goals> Goals { get; set; }
        public virtual DbSet<GoalStatus> GoalStatus { get; set; }
        public virtual DbSet<GroupComments> GroupComments { get; set; }
        public virtual DbSet<GroupCommentUsers> GroupCommentUsers { get; set; }
        public virtual DbSet<GroupGoals> GroupGoals { get; set; }
        public virtual DbSet<GroupInvitations> GroupInvitations { get; set; }
        public virtual DbSet<GroupRequests> GroupRequests { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<GroupUpdates> GroupUpdates { get; set; }
        public virtual DbSet<GroupUpdateSupports> GroupUpdateSupports { get; set; }
        public virtual DbSet<GroupUpdateUsers> GroupUpdateUsers { get; set; }
        public virtual DbSet<GroupUsers> GroupUsers { get; set; }
        public virtual DbSet<Metrics> Metrics { get; set; }
        public virtual DbSet<RegistrationTokens> RegistrationTokens { get; set; }
        public virtual DbSet<SecurityTokens> SecurityTokens { get; set; }
        public virtual DbSet<SupportInvitations> SupportInvitations { get; set; }
        public virtual DbSet<Supports> Supports { get; set; }
        public virtual DbSet<Updates> Updates { get; set; }
        public virtual DbSet<UpdateSupports> UpdateSupports { get; set; }
        public virtual DbSet<UserProfiles> UserProfiles { get; set; }
    }
}
